In [1]:
import pandas as pd
import numpy as np
import re

# Notebook 1: Make the new field-based dataset, including additional river data

Notebook to combine different field-based data sources into a new updated dataset. Data to combine:
- C2016 field-based data, excluding lakes
- E2017 lake data
- Newly gathered river and stream data

Make datasets uniform and add metadata.

# Read in data

In [2]:
keep_cols = ['Type', 'Site', 'Lat', 'Lon', 'tau', 'mo_mi', 'Ref']

# Read in Catalan et al. (2016) data and drop bioassay data
# and field data from lakes and reservoirs

data_fpath = r"data/input_data/catalan_2016_doc_data.xlsx"
cat_df_full = pd.read_excel(data_fpath, usecols="A:M")

cat_df_full.rename(
    {
        "WRT (years) ": "tau",
        "Degradation rate temperature corrected (d-1)": "k_per_day",
        "FieldII": "Method",
        "Type": "Full_type",
        "System10": "Type",
        "Latitude (d.d.)": 'Lat',
        "Longitude (d.d.)": 'Lon',
        "Cite": "Ref",
    },
    axis="columns",
    inplace=True,
)

# Sort by tau for plotting later
cat_df_full = cat_df_full.sort_values(by="tau")

# Derive variables (don't trust variables derived in Excel from their data when playing around in case errors crept in)
cat_df_full["k"] = cat_df_full["k_per_day"] * 365
cat_df_full["mo_mi"] = np.exp(-cat_df_full["k"] * cat_df_full["tau"])

# Drop bioassay data
cat_df = cat_df_full.loc[cat_df_full["Method"] == "FieldModel", keep_cols+['Excluded from analysis']]

# Drop lake and reservoir data (instead use data from Evans et al. 2017)
cat_df = cat_df[~cat_df['Type'].isin(['Lake', 'Reservoir'])]

# For plotting later, get field data that Catalan et al. didn't include in stats, but did plot
ocean_df = cat_df.loc[cat_df["Excluded from analysis"] == 1, keep_cols].copy()

# Drop data that Catalan et al. excluded from their regression analyses, for comparability
# (of the field data, this is just oceanic data)
cat_df = cat_df.loc[cat_df["Excluded from analysis"] == 0, keep_cols].copy()

# Calculate site means where have multi-year (or maybe depth) data
duplicates = cat_df[cat_df.duplicated('Site')]
print("\nDuplicates in the 'Site' column; means calculated:")
print(duplicates)

# Group by 'Site' and calculate mean for numeric columns
agg_dict = {'Type': 'first', 'Lat': 'mean', 'Lon': 'mean', 'tau': 'mean', 'mo_mi': 'mean', 'Ref': 'first'}
cat_df = cat_df.groupby('Site').agg(agg_dict).reset_index()

# Add "source" column
cat_df['Source'] = "C2016"

# Add country information manually
country_site_dict = {'Cheesapeake bay': 'USA',
                     'Gironde': 'France',
                     'Hudson261-44 km': 'USA',
                     'Roaring brook': 'USA'}

cat_df['Country'] = cat_df['Site'].map(country_site_dict)
cat_df['Country'] = cat_df['Country'].fillna('Sweden')  # for all other sites

Duplicates in the 'Site' column; means calculated:
        Type           Site        Lat        Lon       tau     mo_mi  \
260    River  Roaring brook  42.489378 -72.524835  0.030137  0.968531
264    River  Roaring brook  42.489378 -72.524835  0.032877  0.699084
265    River  Roaring brook  42.489378 -72.524835  0.032877  0.402985
263    River  Roaring brook  42.489378 -72.524835  0.038356  0.369845
262    River  Roaring brook  42.489378 -72.524835  0.038356  0.699275
267  Estuary        Gironde  45.399414  -0.799456  1.500000  0.888889

                      Ref
260  McDowell et al. 1976
264  McDowell et al. 1976
265  McDowell et al. 1976
263  McDowell et al. 1976
262  McDowell et al. 1976
267    Huguet et al. 2009

In [14]:
# Take a look at the result
# cat_df

In [4]:
# Quick look at the oceanic data and save for plotting later
ocean_df.to_csv(r'data/input_data/C2016_oceanic_data.csv', index=False)
ocean_df

,Type,Site,Lat,Lon,tau,mo_mi,Ref
331,Ocean,Arctic (Beaufort Gyre),81.308321,-147.355961,12.5,0.297453,Hansell et al. 2004
332,Ocean,Arctic,83.194896,105.769039,30.0,0.910448,Anderson et al.1998
329,Ocean,Greenland to North Atlantic,63.937373,-34.127199,80.0,0.908333,"Hansell and Carlson, 1998"
328,Ocean,Nordic seas,57.302790,2.981872,128.0,0.976676,Jeansson et al. 2011
330,Ocean,Greenland to North Atlantic,63.937373,-34.127199,595.0,0.814458,"Hansell and Carlson, 1998"

In [5]:
# Read in lake and reservoir data from Evans et al. (2017)
data_fpath = r"data/input_data/evans_2017_doc_retention_cleaned.csv"
ev_df = pd.read_csv(data_fpath)

if "Country" not in keep_cols:
    keep_cols += ["Country"]

# Rename for compatibility with other data
ev_df = ev_df.rename(
    {
        "Name": "Site",
        "Type": "Type",
        "WRT_yr": "tau",
        "Latitude": "Lat",
        "Longitude": "Lon",
        "References": "Ref",
    },
    axis="columns",
)

ev_df.sort_values("tau", inplace=True)

# Drop any NANs in tau or RDOC
ev_df = ev_df.dropna(how="any", subset=["tau", "R_DOC"])

# Drop negative retention values
# Evans et al. defined net sink lakes as having RDOC > 0.1. I will use
# a more lenient definition, with a threshold of 0, as I model transmission in the range 0-1
ev_df = ev_df.query("R_DOC > 0")

# Test sensitivity to two lakes with high tau
# ev_df = ev_df.query("tau < 100")

# Calculate transmission (in case of mistakes in excel, go back to raw data)
ev_df["mo_mi"] = 1 - ev_df["R_DOC"]

ev_df = ev_df[keep_cols]

# Add "source" column
ev_df["Source"] = "E2017"

# Update "Ref" column to point to E2017 paper
ev_df["Ref"] = ev_df["Source"] + " (" + ev_df["Ref"] + ")"


# Convert coordinates to decimal degrees
def dms_to_dd(dms_str):
    # Extract degrees, minutes, and direction using regex
    match = re.match(r"(\d+)°\s*(\d+)ʹ\s*([NSEW])", dms_str)
    if not match:
        return None
    degrees, minutes, direction = match.groups()
    dd = float(degrees) + float(minutes) / 60
    if direction in ['S', 'W']:
        dd *= -1
    return dd


# Apply conversion
ev_df['Lat'] = ev_df['Lat'].apply(dms_to_dd)
ev_df['Lon'] = ev_df['Lon'].apply(dms_to_dd)

In [13]:
# Take a look
# ev_df

In [7]:
# Read in extra riv data (reviewed by me)
riv_df = pd.read_csv(r'data/input_data/review_instream_doc_retention_summary.csv')
riv_df['tau'] = riv_df['t (days)'] / 365  # tau in years
riv_df['Type'] = 'River'
riv_df.rename({'Transmission (M_out/M_in)': 'mo_mi'},
              axis=1, inplace=True)

# Drop data associated with natural DOM addition experiments
riv_df = riv_df.loc[riv_df['Exclude_expts'] == 0]

riv_df = riv_df[keep_cols]

# Add source info
riv_df['Source'] = 'This study'

riv_df.head()

,Type,Site,Lat,Lon,tau,mo_mi,Ref,Country,Source
0,River,"Fluvià River, NE Spain",42.189200,2.767300,0.000685,1.000000,Casas-Ruiz et al. (2017),Spain,This study
1,River,"Wood Brook, England",52.800938,-2.305389,0.000249,0.982609,Khamis et al. (2021),UK,This study
2,River,"Creeping Swamp, North Carolina",35.415000,-77.193000,0.025368,0.360000,Mulholland (1981),USA,This study
3,River,"Fort River, Massachusetts",42.336000,-72.574000,0.000363,0.960000,Fisher (1977),USA,This study
4,River,"Tianmu Lake catchment, SE China",31.222847,119.391676,0.002426,0.713333,Gong et al. (2021),China,This study

# Combine data and save

In [8]:
# Concatenate the three dataframes
df = pd.concat([cat_df, ev_df, riv_df])

# Clean up some remaining messiness in the string columns
df['Type'] = df['Type'].str.strip().str.lower()
df['Type'] = df['Type'].replace('lake*', 'lake')

# Check for duplicates in the 'Site' column
duplicates = df[df.duplicated('Site', keep=False)]
if len(duplicates) > 0:
    # duplicates.to_csv('duplicates.csv')
    print("\nDuplicates in the 'Site' column:")
    print(duplicates)
else:
    print('No site duplicates')

# Save
df.to_csv(r'data/combined_data_2025-09.csv', index=False)

df

No site duplicates

,Site,Type,Lat,Lon,tau,mo_mi,Ref,Source,Country
0,1,catchment,68.345160,21.366472,1.400000,0.630,Algesten et al. 2003,C2016,Sweden
1,2,catchment,67.343565,21.824873,0.500000,0.680,Algesten et al. 2003,C2016,Sweden
2,3,catchment,65.904611,22.465105,0.500000,0.690,Algesten et al. 2003,C2016,Sweden
3,4,catchment,66.984499,20.905047,0.500000,0.560,Algesten et al. 2003,C2016,Sweden
4,5,catchment,67.511340,17.477312,2.600000,0.530,Algesten et al. 2003,C2016,Sweden
...,...,...,...,...,...,...,...,...,...
6,"Glensaugh, Scotland",river,56.906198,-2.558902,0.000114,0.770,Demars (2019),This study,UK
7,"River Ipswich, Massachusetts, USA",river,42.677269,-70.837892,0.013699,0.850,Wollheim et al. (2015),This study,USA
8,"Brocky Burn, NE Scotland",river,56.941710,-2.638110,0.000576,0.863,Dawson et al. (2001),This study,UK
9,"River Tees, England",river,54.518700,-1.602430,0.007991,0.415,Moody et al. (2013),This study,UK
10,"Trout Beck, England",river,54.696750,-2.375260,0.000491,0.710,Moody et al. (2016),This study,UK

# Quick description of the data

In [9]:
print(df[['Type', 'tau', 'mo_mi']].describe())

              tau      mo_mi
count   92.000000  92.000000
mean    11.447519   0.613644
std     73.909324   0.211194
min      0.000114   0.096000
25%      0.245000   0.477500
50%      1.300000   0.589500
75%      2.512500   0.769250
max    692.000000   1.000000

In [10]:
stats_df = df[['Type', 'mo_mi', 'tau']].groupby('Type').describe()
stats_df.to_csv(r'data/stats/compiled-data-stats.csv')

stats_df

          mo_mi                                                           \
          count      mean       std    min       25%       50%       75%
Type
catchment  21.0  0.486190  0.132721  0.230  0.390000  0.490000  0.560000
estuary     2.0  0.606342  0.150391  0.500  0.553171  0.606342  0.659514
lake       48.0  0.593271  0.203996  0.096  0.487250  0.578500  0.699250
reservoir   7.0  0.818143  0.165539  0.553  0.731000  0.789000  0.962500
river      14.0  0.773469  0.206086  0.360  0.668333  0.810000  0.948020

                      tau                                             \
                max count       mean         std       min       25%
Type
catchment  0.690000  21.0   2.852381    3.089275  0.400000  1.000000
estuary    0.712685   2.0   1.236301    0.372926  0.972603  1.104452
lake       0.994000  48.0  20.584583  101.943455  0.070000  0.715000
reservoir  0.998000   7.0   0.357143    0.426877  0.050000  0.150000
river      1.000000  14.0   0.017083    0.039103  0.000114  0.000512


                50%       75%         max
Type
catchment  2.100000  3.100000   13.500000
estuary    1.236301  1.368151    1.500000
lake       1.680000  2.825000  692.000000
reservoir  0.230000  0.310000    1.300000
river      0.001934  0.012272    0.148356

In [11]:
df[['Source', 'tau', 'mo_mi']].groupby('Source').describe()

             tau                                                      \
           count       mean        std       min       25%       50%
Source
C2016       26.0   2.406091   2.928672  0.005479  0.525000  1.750000
E2017       55.0  18.010182  95.349903  0.050000  0.385000  1.590000
This study  11.0   0.004855   0.008031  0.000114  0.000427  0.000685

                                 mo_mi                                       \
                 75%         max count      mean       std    min       25%
Source
C2016       2.575000   13.500000  26.0  0.537418  0.179141  0.230  0.432500
E2017       2.625000  692.000000  55.0  0.621891  0.212097  0.096  0.508500
This study  0.005209    0.025368  11.0  0.752581  0.214523  0.360  0.682222


              50%       75%     max
Source
C2016       0.505  0.647625  0.9976
E2017       0.591  0.777000  0.9980
This study  0.770  0.911500  1.0000

In [12]:
df[['Country', 'Type', 'tau', 'mo_mi']].groupby('Country').describe()

                 tau                                                \
               count        mean       std         min         25%
Country
Canada          21.0    4.554762  5.056058    0.700000    1.700000
China            2.0    0.001934  0.000696    0.001442    0.001688
Czech Republic   2.0    1.150000  0.636396    0.700000    0.925000
Finland          4.0    1.312500  1.400437    0.070000    0.115000
France           2.0    0.775000  1.025305    0.050000    0.412500
Japan            1.0    5.500000       NaN    5.500000    5.500000
Malawi           1.0  692.000000       NaN  692.000000  692.000000
Norway           5.0    0.678000  1.020843    0.100000    0.100000
Spain            1.0    0.000685       NaN    0.000685    0.000685
Sweden          30.0    2.333849  2.723386    0.005479    0.770000
Switzerland      1.0    1.000000       NaN    1.000000    1.000000
UK              10.0    0.266942  0.470093    0.000114    0.000512
USA             11.0    0.349300  0.496346    0.000363    0.028642
USA/Canada       1.0  170.000000       NaN  170.000000  170.000000

                                                   mo_mi                      \
                       50%         75%         max count      mean       std
Country
Canada            2.610000    5.670000   19.300000  21.0  0.554190  0.135207
China             0.001934    0.002180    0.002426   2.0  0.683889  0.041641
Czech Republic    1.150000    1.375000    1.600000   2.0  0.599500  0.047376
Finland           1.315000    2.512500    2.550000   4.0  0.774000  0.132275
France            0.775000    1.137500    1.500000   2.0  0.855342  0.201748
Japan             5.500000    5.500000    5.500000   1.0  0.961000       NaN
Malawi          692.000000  692.000000  692.000000   1.0  0.096000       NaN
Norway            0.320000    0.380000    2.490000   5.0  0.724600  0.194892
Spain             0.000685    0.000685    0.000685   1.0  1.000000       NaN
Sweden            1.690000    2.575000   13.500000  30.0  0.514853  0.167969
Switzerland       1.000000    1.000000    1.000000   1.0  0.620000       NaN
UK                0.063995    0.325000    1.530000  10.0  0.728661  0.194707
USA               0.180000    0.325000    1.590000  11.0  0.750598  0.232231
USA/Canada      170.000000  170.000000  170.000000   1.0  0.155000       NaN


                     min       25%       50%       75%       max
Country
Canada          0.291000  0.461000  0.563000  0.630000  0.790000
China           0.654444  0.669167  0.683889  0.698611  0.713333
Czech Republic  0.566000  0.582750  0.599500  0.616250  0.633000
Finland         0.591000  0.731250  0.801500  0.844250  0.902000
France          0.712685  0.784014  0.855342  0.926671  0.998000
Japan           0.961000  0.961000  0.961000  0.961000  0.961000
Malawi          0.096000  0.096000  0.096000  0.096000  0.096000
Norway          0.546000  0.572000  0.650000  0.861000  0.994000
Spain           1.000000  1.000000  1.000000  1.000000  1.000000
Sweden          0.230000  0.400000  0.505000  0.614000  0.997600
Switzerland     0.620000  0.620000  0.620000  0.620000  0.620000
UK              0.415000  0.560750  0.773000  0.844500  0.982609
USA             0.360000  0.570250  0.850000  0.950500  0.993000
USA/Canada      0.155000  0.155000  0.155000  0.155000  0.155000